name: shopos
description: POS and accounts ledger.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.2+7

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  flutter_barcode_listener: ^0.1.4
  shared_preferences: ^2.1.2
  audioplayers: ^3.0.1
  cached_network_image: ^3.2.1
  cookie_jar: any
  date_time_picker: 
  dio: ^5.1.1
  dio_cookie_manager: any
  htmltopdfwidgets:
  lottie:
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.0.1

  flutter_html_to_pdf: ^0.7.0
  file_picker:
  file_saver:
  # flutter_localizations:
  # flutter_secure_storage: ^5.0.2
  flutter_typeahead: ^4.3.7
  flutter_vibrate: ^1.3.0
  get_it: ^7.2.0
  image_picker:
  crop_image:
  in_app_update: ^4.0.1
  intl: 
  path_provider: ^2.0.9
  pdf: ^3.7.4
  permission_handler: ^10.2.0
  pin_code_fields: ^7.4.0
  share_plus:
  slidable_button: ^2.0.0+1
  whatsapp_share2: ^2.0.2
  rflutter_alert: ^2.0.4
  flutter_svg: ^2.0.4
  flutter_pdfview: ^1.2.2
  url_launcher: ^6.1.3
  new_version: ^0.3.1
  switcher: ^1.0.0
  screenshot: 
  webview_universal: ^0.0.5
  open_app_file: ^4.0.2
  ntp: ^2.0.0
  provider: ^6.0.5
  syncfusion_flutter_xlsio:
  sqflite:
 
 


msix_config:
  display_name: Flutter App
  publisher_display_name: Company Name
  identity_name: company.suite.flutterapp
  msix_version: 1.0.0.0
  logo_path: F:\Coding\flutter\CUBE-desktop\windows\runner\resources\app_icon.ico
  capabilities: internetClient, location

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.0
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/CUBE.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/audio/
    - assets/icon/
    - assets/anims/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf
    - family: Montserrat
      fonts:
        - asset: assets/OpenSans-Regular.ttf    